export const GET_FANDOMS_START = 'GET_FANDOMS_START';
export const GET_FANDOMS_SUCCESS = 'GET_FANDOMS_SUCCESS';
export const GET_FANDOMS_FAIL = 'GET_FANDOMS_FAIL';
export const GET_FANDOM = 'GET_FANDOM';

export const EDIT_FANDOM_START = 'EDIT_FANDOM_START';
export const EDIT_FANDOM_SUCCESS = 'EDIT_FANDOM_SUCCESS';
export const EDIT_FANDOM_FAIL = 'EDIT_FANDOM_FAIL';


export const GET_FANFICS_START = 'GET_FANFICS_START';
export const GET_FANFICS_SUCCESS = 'GET_FANFICS_SUCCESS';
export const GET_FANFICS_FAIL = 'GET_FANFICS_FAIL';