export const GET_FANDOMS_START = 'GET_FANDOMS_START';
export const GET_FANDOMS_SUCCESS = 'GET_FANDOMS_SUCCESS';
export const GET_FANDOMS_FAIL = 'GET_FANDOMS_FAIL';
export const GET_FANDOM = 'GET_FANDOM';

export const EDIT_FANDOM_START = 'EDIT_FANDOM_START';
export const EDIT_FANDOM_SUCCESS = 'EDIT_FANDOM_SUCCESS';
export const EDIT_FANDOM_FAIL = 'EDIT_FANDOM_FAIL';


export const GET_FANFICS_START = 'GET_FANFICS_START';
export const GET_FANFICS_SUCCESS = 'GET_FANFICS_SUCCESS';
export const GET_FANFICS_FAIL = 'GET_FANFICS_FAIL';

export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_USER_FANFICS_DATA_SUCCESS = "GET_USER_FANFICS_DATA_SUCCESS";
export const GET_USER_FANFICS_DATA_FAIL = "GET_USER_FANFICS_DATA_FAIL";

export const GET_FILTERED_FANFICS_SUCCESS='GET_FILTERED_FANFICS_SUCCESS';
export const GET_FILTERED_FANFICS_FAIL='GET_FILTERED_FANFICS_FAIL';